[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio 
lib_deps =
    adafruit/Adafruit BusIO @ ^1.17.4
    bblanchon/ArduinoJson 
    olikraus/U8g2 @ ^2.34.0
    h2zero/NimBLE-Arduino @ ^2.5.0
    mikalhart/TinyGPSPlus@^1.0.3
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = post:merge_bin.py

